### ISSUE TITLE
Undefined property $exception 

### ISSUE THREAD

**Issue by stickeepaul** [stickeeuk/instrumentation#21]
When using this package in a Laravel project that uses CORS you run into the following error:

```
[2023-08-09 15:53:42] local.ERROR: Undefined property: Symfony\Component\HttpFoundation\Response::$exception {"exception":"[object] (ErrorException(code: 0): Undefined property: Symfony\\Component\\HttpFoundation\\Response::$exception at /var/www/html/vendor/stickee/instrumentation/src/Laravel/Http/Middleware/InstrumentationResponseTimeMiddleware.php:20)
[stacktrace]
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(270): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 /var/www/html/vendor/stickee/instrumentation/src/Laravel/Http/Middleware/InstrumentationResponseTimeMiddleware.php(20): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->Illuminate\\Foundation\\Bootstrap\\{closure}()
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Stickee\\Instrumentation\\Laravel\\Http\\Middleware\\InstrumentationResponseTimeMiddleware->handle()
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(165): Illuminate\\Pipeline\\Pipeline->then()
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(134): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#6 /var/www/html/public/index.php(58): Illuminate\\Foundation\\Http\\Kernel->handle()
#7 /var/www/html/server.php(21): require_once('...')
#8 {main}
"} 
```

This is because [the response to the preflight request](https://github.com/laravel/framework/blob/fc186a64b12a325de288a7f400d9e2712b7ce476/src/Illuminate/Http/Middleware/HandleCors.php#L54-L55) is an instance of [`Symfony\Component\HttpFoundation\Response`](https://github.com/fruitcake/php-cors/blob/22e07135007e203c16d6cb56d97a743fe5763649/src/CorsService.php#L146) and not the expected `Illuminate\Http\Response` (which has the `$exception` property available via `Illuminate/Http/ResponseTrait`).

**Comment by stickeepaul** [comment]
I have a fix in mind for this, I'll write it up now
